### ISSUE TITLE
Helical Endcap Fastening

### ISSUE THREAD

**Issue by paperman5** [oresat/oresat-structure#10]
There is currently no way that I see for the helical antenna end cap to be fastened to the end of the satellite:
![image](https://cloud.githubusercontent.com/assets/22630098/26648004/ef56621a-45f5-11e7-9883-569982b08f3d.png)
A possible way to fix this would be to add supports underneath the endcap coming out of the sides of the rail assembly. However I need to confirm that this is allowable as I am not sure of the rail requirements and it would impose some (still generous) vertical restrictions for the solar panel card that I believe goes under the endcap. I was thinking something like this:
![image](https://cloud.githubusercontent.com/assets/22630098/26648500/8551fb34-45f7-11e7-82fb-d12133fe7a6f.png)
Does this seem reasonable? If it does, I will go ahead and make these changes.

**Comment by andrewgreenberg** [comment]
Huh, this is an interesting problem. First, the end cap has to be mostly a solid PCB, since it's the ground plane for the helical antenna. Second, the helical antenna can't be "embedded" in the PCB, it has to go start from that ground plane. So you'll have to drop the end cap "into" the satellite body if you need more than the 6.5mm height from the top of the frame to the top of the rails.

Your proposal seems fine to me. I approve if Joe approves. One thought: can we squish "out" the coiled up helical so it fits in the 6.5 mm space? That means slightly "unwinding" the helical as it gets compressed, but that seems OK?

**Comment by Joedang** [comment]
So, I made some endcap boards that just sit on top of the structure. They screw into the rack and register with the rails with 0.1 mm of clearance (so, 0.2 mm of slop in X and Y).

It's worth noting that with the mezzanine connections to the head/tail cards (see #12 and #13), we loose some real estate for antennas.

## +Z face:
![image](https://user-images.githubusercontent.com/16861664/31296075-e727b706-aa95-11e7-924a-740ed563b7a5.png)

## -Z face:
![image](https://user-images.githubusercontent.com/16861664/31296118-0badd7ea-aa96-11e7-8940-ed7d56238b90.png)

## -X corners:
![image](https://user-images.githubusercontent.com/16861664/31296179-39379430-aa96-11e7-98e3-6c681834257e.png)

## +X corners:
![image](https://user-images.githubusercontent.com/16861664/31296212-543591ba-aa96-11e7-943b-4479739ab7d5.png)

**Comment by Joedang** [comment]
Update from the Greenberg:  
Osh Park guarantees features that can be done with a 0.1" (yes, 1/10 inch, not 0.1 mm) endmill. So, the dogbones would need to be no larger than 0.05" (1.27 mm) in radius. I think they're 1 mm in radius right now, so I'll have to go in and change them.

**Comment by Joedang** [comment]
I updated the radius of the dogbone fillets. The original issue has been addressed, and I assume that any if additional changes are needed, they will be brought up by the capstone. [So, here I go closing again. ](https://youtu.be/YG6DifUtPvs)
